/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Geometry;

import java.util.Scanner;

public class Geometry {

	int choice1;
	static int choice2;
	int choice3;
	private static float A2;
	private static float B2;
	private static float A1;
	private static float B1;
	private static float C2;
	private static int choice22;
	
//	@Test
//	public void UI() {
		
		
	public static void main(String[] args) {
		
		
		
		Scanner in = new Scanner(System.in);
		System.out.println("Press 1 to calculate for rectangle/nPress 2 to calculate for a a sphere");
		int choice1 = in.nextInt();
		
		
		if (choice1 == 1) {
			System.out.println("Press 1 to calculate the area/nPress 2 to calculate the perimeter");
			choice22 = in.nextInt();
		}
		if (choice1 == 2) {
			System.out.println("Press 1 to calculate the volume/nPress 2 to calculate the surface area");
			choice22 = in.nextInt();
		}
		

		
		if (choice2 == 1) {

			System.out.println("Enter Width:");
			setA2(in.nextFloat());
			System.out.println("Enter Height:");
			setB2(in.nextFloat());
			areaRect(A2, B2);
			System.out.println(Geometry.areaRect(A2, B2));
		}
		

		
		if (choice2 == 1) {

			System.out.println("Enter Width:");
			setA1(in.nextFloat());
			System.out.println("Enter Height:");
			setB1(in.nextFloat());
			perimeterRect(A1, B1);
			System.out.println(Geometry.perimeterRect(A1, B1));
		}
	

		
		if (choice22 == 1) {

			System.out.println("Enter Radius:");
			setC2(in.nextFloat());
			volumeSphere(C2);
			System.out.println(Geometry.volumeSphere(C2));
		}

		
		
		if (choice22 == 2) {

			System.out.println("Enter Radius:");
			setC2(in.nextFloat());
			surfaceAreaSphere(C2);
			System.out.println(Geometry.surfaceAreaSphere(C2));
			in.close();
		}
		
		
		}
		

	public static float areaRect(float A2, float B2) {
		float D2 = A2 * B2;
		return D2;
	}

	
	public static float perimeterRect(float A1, float B1) {	
		float E2 = A1 + A1 + B1 + B1;
		return E2;
	}
	
	
	public static float volumeSphere(float C2) {
		float F2 = (4/3) * (22/7) * (C2 * C2 * C2);
		return F2;
	}

	
	public static float surfaceAreaSphere(float C2) {
		float G2 = 4 * (22/7) * (C2 * C2);
		return G2;
	}
	

	

	public static float getA2() {
		return A2;
		
	}



	public static void setA2(float a2) {
		Geometry.A2 = a2;
	}


	public static float getB2() {
		return B2;
	}



	public static void setB2(float b2) {
		Geometry.B2 = b2;
	}



	public static float getA1() {
		return A1;
	}



	public static void setA1(float a1) {
		Geometry.A1 = a1;
	}



	public static float getB1() {
		return B1;
	}


	public static void setB1(float b1) {
		Geometry.B1 = b1;
	}



	public static float getC2() {
		return C2;
	}



	public static void setC2(float c2) {
		Geometry.C2 = c2;
	}
}


		
	
		

